/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeckSelect.java
 *
 * Created on 20-Dec-2011, 2:57:45 AM
 */

package flashcard;

/**
 *
 * @author GiantChiprel
 */
public class DeckSelect extends javax.swing.JFrame {

    /** Creates new form DeckSelect */
    public DeckSelect() {
        initComponents();
    }

    private void selectDeck(int num)
    {
        FlashcardView.model.deckSelected = num;
        FlashcardView.TestText.setText("Deck "+num+" selected!");
        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectionText = new javax.swing.JLabel();
        programTitle = new javax.swing.JLabel();
        deck3Button = new javax.swing.JButton();
        deck2Button = new javax.swing.JButton();
        deck1Button = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flashcard.FlashcardApp.class).getContext().getResourceMap(DeckSelect.class);
        setTitle(resourceMap.getString("DeckSelect.title")); // NOI18N
        setName("DeckSelect"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        selectionText.setFont(resourceMap.getFont("selectionText.font")); // NOI18N
        selectionText.setText(resourceMap.getString("selectionText.text")); // NOI18N
        selectionText.setName("selectionText"); // NOI18N

        programTitle.setFont(resourceMap.getFont("programTitle.font")); // NOI18N
        programTitle.setText(resourceMap.getString("programTitle.text")); // NOI18N
        programTitle.setName("programTitle"); // NOI18N

        deck3Button.setText(resourceMap.getString("deck3Button.text")); // NOI18N
        deck3Button.setName("deck3Button"); // NOI18N
        deck3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deck3ButtonActionPerformed(evt);
            }
        });

        deck2Button.setText(resourceMap.getString("deck2Button.text")); // NOI18N
        deck2Button.setName("deck2Button"); // NOI18N
        deck2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deck2ButtonActionPerformed(evt);
            }
        });

        deck1Button.setText(resourceMap.getString("deck1Button.text")); // NOI18N
        deck1Button.setName("deck1Button"); // NOI18N
        deck1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deck1ButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setText(resourceMap.getString("mainMenuButton.text")); // NOI18N
        mainMenuButton.setName("mainMenuButton"); // NOI18N
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(programTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(selectionText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(deck1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(deck2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(deck3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deck1Button, deck2Button, deck3Button, mainMenuButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(programTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(selectionText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(502, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(331, 331, 331)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deck1Button, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addComponent(deck2Button, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addComponent(deck3Button, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addGap(90, 90, 90)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deck1Button, deck2Button, deck3Button, mainMenuButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deck1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deck1ButtonActionPerformed
        // TODO add your handling code here:
        //Set deck to 1 and return to main menu
        selectDeck(1);
    }//GEN-LAST:event_deck1ButtonActionPerformed

    private void deck2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deck2ButtonActionPerformed
        // TODO add your handling code here:
        //Set deck to 2 and return to main menu
        selectDeck(2);
    }//GEN-LAST:event_deck2ButtonActionPerformed

    private void deck3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deck3ButtonActionPerformed
        // TODO add your handling code here:
        //Set deck to 3 and return to main menu
        selectDeck(3);
    }//GEN-LAST:event_deck3ButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeckSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deck1Button;
    private javax.swing.JButton deck2Button;
    private javax.swing.JButton deck3Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JLabel programTitle;
    private javax.swing.JLabel selectionText;
    // End of variables declaration//GEN-END:variables

}
